/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package venta.de.medicamentos;

/**
 *
 * @author Administrador
 */
public class VentanaP extends javax.swing.JFrame {

    /**
     * Creates new form VentanaP
     */
    public VentanaP() {
        initComponents();
        login lp = new login(this,true);
        lp.setVisible(true);
        
        if(lp.tipo == 2){
            this.mnuEmpleado.setVisible(false);
            this.mnibusEmpleado.setVisible(false);
            this.mnibusSexo.setVisible(false);
            this.mnibusTipo.setVisible(false);
        }//fin if
        
        if(lp.tipo == 3){
            this.mnuEmpleado.setVisible(false);
            this.mnibusEmpleado.setVisible(false);
            this.mnibusSexo.setVisible(false);
            this.mnibusTipo.setVisible(false);
        }//fin if
        
        if(lp.tipo == 4){
            this.mnuEmpleado.setVisible(false);
            this.mnibusEmpleado.setVisible(false);
            this.mnibusSexo.setVisible(false);
            this.mnibusTipo.setVisible(false);
        }//fin if
        
    }//fin ventanaP

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniMedicamentos = new javax.swing.JMenuItem();
        mniLaboratorio = new javax.swing.JMenuItem();
        mniReceta = new javax.swing.JMenuItem();
        mnuEmpleado = new javax.swing.JMenu();
        mniEmpleados = new javax.swing.JMenuItem();
        mniTipUsuario = new javax.swing.JMenuItem();
        mniSexo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mniValorUni = new javax.swing.JMenuItem();
        mniVenta = new javax.swing.JMenuItem();
        mniDetalle = new javax.swing.JMenuItem();
        mniListado = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mniCalculo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnibusMedicamentos = new javax.swing.JMenuItem();
        mnibusDetalle = new javax.swing.JMenuItem();
        mnibusEmpleado = new javax.swing.JMenuItem();
        mnibusLaboratorio = new javax.swing.JMenuItem();
        mnibusReceta = new javax.swing.JMenuItem();
        mnibusSexo = new javax.swing.JMenuItem();
        mnibusTipo = new javax.swing.JMenuItem();
        mnibusValor = new javax.swing.JMenuItem();
        mnibusVentas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mniConsulta = new javax.swing.JMenuItem();
        mniAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dp.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        jMenuBar2.setForeground(new java.awt.Color(0, 0, 255));

        jMenu3.setText("Archivo");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        jMenu3.add(mniSalir);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Medicamentos");

        mniMedicamentos.setText("Medicamentos");
        mniMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMedicamentosActionPerformed(evt);
            }
        });
        jMenu4.add(mniMedicamentos);

        mniLaboratorio.setText("Laboratorio");
        mniLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLaboratorioActionPerformed(evt);
            }
        });
        jMenu4.add(mniLaboratorio);

        mniReceta.setText("Receta");
        mniReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRecetaActionPerformed(evt);
            }
        });
        jMenu4.add(mniReceta);

        jMenuBar2.add(jMenu4);

        mnuEmpleado.setText("Empleado");

        mniEmpleados.setText("Empleados");
        mniEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleadosActionPerformed(evt);
            }
        });
        mnuEmpleado.add(mniEmpleados);

        mniTipUsuario.setText("Tipo Usuario");
        mniTipUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTipUsuarioActionPerformed(evt);
            }
        });
        mnuEmpleado.add(mniTipUsuario);

        mniSexo.setText("Sexo");
        mniSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSexoActionPerformed(evt);
            }
        });
        mnuEmpleado.add(mniSexo);

        jMenuBar2.add(mnuEmpleado);

        jMenu6.setText("Venta");

        mniValorUni.setText("Valor unidad");
        mniValorUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniValorUniActionPerformed(evt);
            }
        });
        jMenu6.add(mniValorUni);

        mniVenta.setText("Venta");
        mniVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentaActionPerformed(evt);
            }
        });
        jMenu6.add(mniVenta);

        mniDetalle.setText("Detalle Venta");
        mniDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDetalleActionPerformed(evt);
            }
        });
        jMenu6.add(mniDetalle);

        mniListado.setText("Listado de Ventas");
        mniListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListadoActionPerformed(evt);
            }
        });
        jMenu6.add(mniListado);

        jMenuBar2.add(jMenu6);

        jMenu8.setText("Descuento");

        mniCalculo.setText("Calculo");
        mniCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCalculoActionPerformed(evt);
            }
        });
        jMenu8.add(mniCalculo);

        jMenuBar2.add(jMenu8);

        jMenu1.setText("Buscar");

        mnibusMedicamentos.setText("Medicamentos");
        mnibusMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusMedicamentosActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusMedicamentos);

        mnibusDetalle.setText("Detalle Venta");
        mnibusDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusDetalleActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusDetalle);

        mnibusEmpleado.setText("Empleado");
        mnibusEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusEmpleado);

        mnibusLaboratorio.setText("Laboratorio");
        mnibusLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusLaboratorioActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusLaboratorio);

        mnibusReceta.setText("Receta");
        mnibusReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusRecetaActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusReceta);

        mnibusSexo.setText("Sexo");
        mnibusSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusSexoActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusSexo);

        mnibusTipo.setText("Tipo usuario");
        mnibusTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusTipoActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusTipo);

        mnibusValor.setText("Valor Unidad");
        mnibusValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusValorActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusValor);

        mnibusVentas.setText("Ventas");
        mnibusVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibusVentasActionPerformed(evt);
            }
        });
        jMenu1.add(mnibusVentas);

        jMenuBar2.add(jMenu1);

        jMenu7.setText("Ayuda");

        mniConsulta.setText("Consultar");
        mniConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultaActionPerformed(evt);
            }
        });
        jMenu7.add(mniConsulta);

        mniAcerca.setText("Acerca de:");
        mniAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAcercaActionPerformed(evt);
            }
        });
        jMenu7.add(mniAcerca);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        // TODO add your handling code here:
        
          System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAcercaActionPerformed
        // TODO add your handling code here:
        
        acercade md = new acercade(this, true);
        md.setVisible(true);
        
    }//GEN-LAST:event_mniAcercaActionPerformed

    private void mniCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCalculoActionPerformed
        // TODO add your handling code here:
        INTCalculo id = new INTCalculo();
        this.dp.add(id);
        id.setVisible(true);
        
    }//GEN-LAST:event_mniCalculoActionPerformed

    private void mniMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMedicamentosActionPerformed
        // TODO add your handling code here:
        INTMedicamentos m = new INTMedicamentos();
        this.dp.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_mniMedicamentosActionPerformed

    private void mniLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLaboratorioActionPerformed
        // TODO add your handling code here:
        INTLaboratorio l = new INTLaboratorio();
        this.dp.add(l);
        l.setVisible(true);
    }//GEN-LAST:event_mniLaboratorioActionPerformed

    private void mniRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRecetaActionPerformed
        // TODO add your handling code here:
        INTReceta r = new INTReceta();
        this.dp.add(r);
        r.setVisible(true);
    }//GEN-LAST:event_mniRecetaActionPerformed

    private void mniEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleadosActionPerformed
        // TODO add your handling code here:
        INTEmpleados e = new INTEmpleados();
        this.dp.add(e);
        e.setVisible(true);
    }//GEN-LAST:event_mniEmpleadosActionPerformed

    private void mniTipUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTipUsuarioActionPerformed
        // TODO add your handling code here:
        INTTipodeUsuario tu = new INTTipodeUsuario();
        this.dp.add(tu);
        tu.setVisible(true);
    }//GEN-LAST:event_mniTipUsuarioActionPerformed

    private void mniSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSexoActionPerformed
        // TODO add your handling code here:
        INTSexo s = new INTSexo();
        this.dp.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_mniSexoActionPerformed

    private void mniValorUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniValorUniActionPerformed
        // TODO add your handling code here:
        INTValorUnidad vu = new INTValorUnidad();
        this.dp.add(vu);
        vu.setVisible(true);
    }//GEN-LAST:event_mniValorUniActionPerformed

    private void mniVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentaActionPerformed
        // TODO add your handling code here:
        INTVenta ve = new INTVenta();
        this.dp.add(ve);
        ve.setVisible(true);
    }//GEN-LAST:event_mniVentaActionPerformed

    private void mniDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDetalleActionPerformed
        // TODO add your handling code here:
        INTDetalleVenta dve = new INTDetalleVenta();
        this.dp.add(dve);
        dve.setVisible(true);
    }//GEN-LAST:event_mniDetalleActionPerformed

    private void mnibusMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusMedicamentosActionPerformed
        // TODO add your handling code here:
        Buscador bsm = new Buscador();
        this.dp.add(bsm);
        bsm.setVisible(true);
    }//GEN-LAST:event_mnibusMedicamentosActionPerformed

    private void mniListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListadoActionPerformed
        // TODO add your handling code here:
        ListadodeVentas lsv = new ListadodeVentas();
        this.dp.add(lsv);
        lsv.setVisible(true);
    }//GEN-LAST:event_mniListadoActionPerformed

    private void mnibusDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusDetalleActionPerformed
        // TODO add your handling code here:
        BuscarDetalle bsd = new BuscarDetalle();
        this.dp.add(bsd);
        bsd.setVisible(true);
    }//GEN-LAST:event_mnibusDetalleActionPerformed

    private void mnibusEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusEmpleadoActionPerformed
        // TODO add your handling code here:
        BuscarEmpleado bse = new BuscarEmpleado();
        this.dp.add(bse);
        bse.setVisible(true);
    }//GEN-LAST:event_mnibusEmpleadoActionPerformed

    private void mnibusLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusLaboratorioActionPerformed
        // TODO add your handling code here:
        BuscarLaboratorio bsl = new BuscarLaboratorio();
        this.dp.add(bsl);
        bsl.setVisible(true);
    }//GEN-LAST:event_mnibusLaboratorioActionPerformed

    private void mnibusRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusRecetaActionPerformed
        // TODO add your handling code here:
        BuscarReceta bsr = new BuscarReceta();
        this.dp.add(bsr);
        bsr.setVisible(true);
    }//GEN-LAST:event_mnibusRecetaActionPerformed

    private void mnibusSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusSexoActionPerformed
        // TODO add your handling code here:
        BuscarSexo bss = new BuscarSexo();
        this.dp.add(bss);
        bss.setVisible(true);
    }//GEN-LAST:event_mnibusSexoActionPerformed

    private void mnibusTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusTipoActionPerformed
        // TODO add your handling code here:
        BuscarTipo bst = new BuscarTipo();
        this.dp.add(bst);
        bst.setVisible(true);
    }//GEN-LAST:event_mnibusTipoActionPerformed

    private void mnibusValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusValorActionPerformed
        // TODO add your handling code here:
        BuscarValor bsv = new BuscarValor();
        this.dp.add(bsv);
        bsv.setVisible(true);
    }//GEN-LAST:event_mnibusValorActionPerformed

    private void mnibusVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibusVentasActionPerformed
        // TODO add your handling code here:
        BuscarVentas bsve = new BuscarVentas();
        this.dp.add(bsve);
        bsve.setVisible(true);
    }//GEN-LAST:event_mnibusVentasActionPerformed

    private void mniConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultaActionPerformed
        // TODO add your handling code here:
        LlenarConsultas lc = new LlenarConsultas(this,true);
        lc.setVisible(true);
    }//GEN-LAST:event_mniConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem mniAcerca;
    private javax.swing.JMenuItem mniCalculo;
    private javax.swing.JMenuItem mniConsulta;
    private javax.swing.JMenuItem mniDetalle;
    private javax.swing.JMenuItem mniEmpleados;
    private javax.swing.JMenuItem mniLaboratorio;
    private javax.swing.JMenuItem mniListado;
    private javax.swing.JMenuItem mniMedicamentos;
    private javax.swing.JMenuItem mniReceta;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniSexo;
    private javax.swing.JMenuItem mniTipUsuario;
    private javax.swing.JMenuItem mniValorUni;
    private javax.swing.JMenuItem mniVenta;
    private javax.swing.JMenuItem mnibusDetalle;
    private javax.swing.JMenuItem mnibusEmpleado;
    private javax.swing.JMenuItem mnibusLaboratorio;
    private javax.swing.JMenuItem mnibusMedicamentos;
    private javax.swing.JMenuItem mnibusReceta;
    private javax.swing.JMenuItem mnibusSexo;
    private javax.swing.JMenuItem mnibusTipo;
    private javax.swing.JMenuItem mnibusValor;
    private javax.swing.JMenuItem mnibusVentas;
    private javax.swing.JMenu mnuEmpleado;
    // End of variables declaration//GEN-END:variables
}
